appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Sh/VwevSP46EnZn3tjozXnPD5dq/7w5ThpHUa2T5MpGp+tqOHa1vQT8Fo3h0ZpZN1xo7ev5VZigBGP+0m0XGw6cM78W6xfRybxWZyqjEQmYZ8x3lkEgo7h9/5vJkdqibXA/ZjqB3eLyYujF8kETCKkW25V10BFaW7xQ1u28SuRizrrIcipPqm8HftaxdSnM1kjYypRxCFHRSkhMvchgsBOQDrqveI7lRVZSElQLxwQ9JEG9h06TYiC6b3WH9kZR9DURJ7fkk6gvr94I8C49KfjpGbtSGH/VNCJ0GlpJuWhsCmc3RTgbIiN3uYeU/8Ta6eV+bB8SWaS2dUzsWhJkk8gFTMIuufA4Bqrh4X+dLwxXygY5ow4OCll0aQtiNakz2nSQ90Lx4BIHr9Thh2m5TUUhc7VnLulLQFIA9TIMBF34hsQ7L9+q7OAtWC6Ijs+skxqtbemsY/Fyuq5bKULmAv0RAUu5f8R4U8iHvwziwIGGaBZAEiW67nkP6yiUtMHby0ZPrmW5oYUc8AXsR1IH0KRKuQ5wIphSulHfxEHdR3S+Qucu6lkf+HF7Rx1AaqQFjth6R+8IVdTO1HDzPXMkE6Ob00lHvVnrvTZ4ALblQWmbMkJUp7FFxPy+YxXXjxjeB68bfLogJuxWF8k/HnSYnif/G89HQWqoMiXoa/hMqULs=}
